---
collections:
  - name: community.zabbix
    version: 2.0.0
  - name: ansible.posix
    version: 1.6.2
  - name: community.general
    version: 3.7.0
  - name: newrelic.newrelic_agents
    version: 1.0.4
