---
- name: K3s Image Prune | Build command
  ansible.builtin.set_fact:
    k3s_image_prune_command: >-
      {{ k3s_image_prune_binary }} ctr -n {{ k3s_image_prune_namespace }} image prune{% if k3s_image_prune_prune_all %} --all{% endif %}{% if k3s_image_prune_extra_args %} {{ k3s_image_prune_extra_args | join(' ') }}{% endif %}
  when: k3s_image_prune_run | bool

- name: K3s Image Prune | Run container image prune
  ansible.builtin.command:
    cmd: "{{ k3s_image_prune_command }}"
  register: k3s_image_prune_result
  changed_when: >-
    (k3s_image_prune_result.stdout ~ k3s_image_prune_result.stderr)
    is search('deleted|removed', ignorecase=True)
  failed_when: k3s_image_prune_result.rc != 0
  when:
    - k3s_image_prune_run | bool
    - not ansible_check_mode
