[project]
name = "automation-ansible"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.2.0",
    "ansible-lint>=25.1.3",
    "ara>=1.7.3",
    "passlib>=1.7.4",
    "pre-commit>=4.1.0",
]
