---
- name: Podman | Initial system cleanup
  ansible.builtin.apt:
    autoremove: yes
    autoclean: yes
  become: true

- name: Podman | Remove old repo file
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list"
    state: absent
  become: true

- name: Podman | Remove old GPG key
  ansible.builtin.file:
    path: "/etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg"
    state: absent
  become: true

- name: Podman | Download Podman repo Release.key
  ansible.builtin.get_url:
    url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_{{ podman_ubuntu_series }}/Release.key"
    dest: /tmp/podman-release.key
    mode: "0644"
  become: true

- name: Podman | Convert Release.key to gpg keyring (dearmor, trusted.gpg.d)
  ansible.builtin.command: >
    gpg --dearmor -o /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg /tmp/podman-release.key
  args:
    creates: /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg
  become: true

- name: Podman | Add Podman Kubic repo (NO signed-by)
  ansible.builtin.apt_repository:
    repo: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_{{ podman_ubuntu_series }}/ /"
    filename: devel:kubic:libcontainers:unstable
    state: present
  become: true

- name: Podman | Clean apt lists and update
  ansible.builtin.apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
  become: true

- name: Podman | Upgrade podman
  ansible.builtin.apt:
    name: podman
    state: latest
  become: true

- name: Podman | Upgrade podman-compose (if uv present)
  ansible.builtin.command: |
    export PATH="/home/{{ podman_user }}/.local/bin:$PATH"
    uv tool upgrade podman-compose
  when: podman_compose_manage
  become: true
  become_user: "{{ podman_user }}"
  ignore_errors: true

- name: Podman | Restart rootless podman service
  ansible.builtin.command: systemctl --user daemon-reload && systemctl --user restart podman.socket podman.service
  become: false
  ignore_errors: true

- name: Podman | Restart root podman service
  ansible.builtin.command: sudo systemctl daemon-reload && sudo systemctl restart podman.socket podman.service
  become: true
  ignore_errors: true
