---
# TO CONNECT TO A NEW SERVER USE:
# MUST INSTALL sshpass ON THE SERVER RUNNING THE ANSIBLE SCRIPT
# ansible_user: user
# ansible_ssh_pass: password
# ansible_ssh_common_args: "-o PreferredAuthentications=password -o PubkeyAuthentication=no -o IdentitiesOnly=yes"
all:
  children:
    vagrant:
      hosts:
        vagrant_vm:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o PubkeyAcceptedKeyTypes=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa"
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    servers:
      hosts:
        archivebox:
          ansible_host: 192.168.86.139
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        hp-laptop:
          ansible_host: hp-laptop-ubuntu.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        adguard:
          ansible_host: adguard.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        pihole2:
          ansible_host: pihole2.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        logging:
          ansible_host: logging.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        prometheus:
          ansible_host: prometheus.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        grafana:
          ansible_host: 192.168.86.106
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        unbound:
          ansible_host: 192.168.86.156
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        unbound-secondary:
          ansible_host: 192.168.86.151
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        netbox:
          ansible_host: 192.168.86.110
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
    db:
      hosts:
        mongodb:
          ansible_host: mongodb.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        postgresql:
          ansible_host: postgresql.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        redis:
          ansible_host: redis.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        mariadb:
          ansible_host: mariadb.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        meilisearch:
          ansible_host: meilisearch.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
    k8s:
      hosts:
        k3s-0:
          ansible_host: vm310.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        k3s-1:
          ansible_host: vm313.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        k3s-2:
          ansible_host: vm314.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        k3s-0-worker:
          ansible_host: vm320.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        k3s-1-worker:
          ansible_host: vm321.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        k3s-2-worker:
          ansible_host: vm322.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        k3s-0-dev:
          ansible_host: 192.168.86.137
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
    oci:
      hosts:
        homelab-oci02:
          ansible_host: homelab-oci02.homelab.lan
          ansible_connection: ssh
          ansible_user: opc
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        homelab-oci03:
          ansible_host: homelab-oci03.homelab.lan
          ansible_connection: ssh
          ansible_user: opc
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
    proxmox:
      hosts:
        proxmox2:
          ansible_host: proxmox2.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        proxmox3:
          ansible_host: proxmox3.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
        proxmox4:
          ansible_host: proxmox4.homelab.lan
          ansible_connection: ssh
          ansible_port: 22
          ansible_user: tbryant
          ansible_ssh_private_key_file: ~/.ssh/id_master_key_nopass
