---
- name: Install npm packages for Helix
  ansible.builtin.shell: |
    export PATH="{{ ansible_env.HOME }}/.cargo/bin:$PATH"
    eval "$(fnm env --use-on-cd)"
    npm install -g {{ item.name }}{{ '@' + item.version if item.version is defined else '' }}
  register: npm_install
  changed_when: npm_install.rc == 0
  failed_when:
    - npm_install.rc != 0
    - "'already installed' not in npm_install.stderr"
    - "'EEXIST' not in npm_install.stderr"
  loop: "{{ helix_npm_packages }}"
  when: helix_state == "present"
  ignore_errors: true
