---
- name: Evaluate rbenv init
  ansible.builtin.shell: |
    export PATH="{{ ansible_env.HOME }}/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    echo $PATH
  register: rbenv_path
  changed_when: false
  args:
    executable: /bin/bash

- name: Set environment for gem commands
  ansible.builtin.set_fact:
    gem_env:
      PATH: "{{ rbenv_path.stdout }}:{{ ansible_env.PATH }}"
      RBENV_VERSION: "{{ ruby_version }}"

- name: Install gem packages
  ansible.builtin.shell: |
    export PATH="{{ ansible_env.HOME }}/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    gem install {{ item }}
  register: gem_install
  loop: "{{ helix_ruby_packages }}"
  failed_when: false
  changed_when: gem_install.rc == 0
  when: helix_state == "present"
  ignore_errors: true
