---
- name: Ensure systemd is installed
  apt:
    name: systemd
    state: present
  become: true

- name: Configure systemd-resolved
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: restart systemd-resolved

- name: Enable and start systemd-resolved
  systemd:
    name: systemd-resolved
    state: started
    enabled: yes
  become: true

- name: Remove old resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent
  become: true

- name: Create symlink for resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  become: true
