---
# Install tasks
- name: Skip sops and age installation on Darwin
  ansible.builtin.debug:
    msg: "Skipping sops and age installation on Darwin - managed through Homebrew"
  when: (sops_state == "present" or age_state == "present")

- name: Initialize Homebrew environment
  ansible.builtin.shell: eval "$(/opt/homebrew/bin/brew shellenv)" && echo $PATH
  register: brew_env
  changed_when: false
  when: (sops_state == "present" or age_state == "present")

- name: Check if sops is available
  ansible.builtin.shell: |
    eval "$(/opt/homebrew/bin/brew shellenv)"
    which sops
  register: sops_check
  changed_when: false
  failed_when: false
  when: sops_state == "present"

- name: Check if age is available
  ansible.builtin.shell: |
    eval "$(/opt/homebrew/bin/brew shellenv)"
    which age
  register: age_check
  changed_when: false
  failed_when: false
  when: age_state == "present"

- name: Fail if sops is not installed
  ansible.builtin.fail:
    msg: "sops could not be found. Please ensure it's installed via Homebrew."
  when: sops_state == "present" and sops_check.rc != 0

- name: Fail if age is not installed
  ansible.builtin.fail:
    msg: "age could not be found. Please ensure it's installed via Homebrew."
  when: age_state == "present" and age_check.rc != 0

# Uninstall tasks
- name: Uninstall sops and age
  ansible.builtin.debug:
    msg: "To uninstall sops and age on Darwin, please remove them from your Brewfile and run 'brew bundle cleanup --force'"
  when: sops_state == "absent" or age_state == "absent"
