---
- name: Skip 1Password CLI installation on Darwin
  ansible.builtin.debug:
    msg: "Skipping 1Password CLI installation on Darwin - managed through Homebrew"
  when: op_state == "present"

- name: Initialize Homebrew environment
  ansible.builtin.shell: eval "$(/opt/homebrew/bin/brew shellenv)" && echo $PATH
  register: brew_env
  changed_when: false
  when: op_state == "present"

- name: Check if op CLI is available
  ansible.builtin.shell: |
    eval "$(/opt/homebrew/bin/brew shellenv)"
    which op
  register: op_check
  changed_when: false
  failed_when: false
  when: op_state == "present"

- name: Fail if 1Password CLI is not installed
  ansible.builtin.fail:
    msg: "1Password CLI could not be found. Please ensure it's installed via Homebrew."
  when: op_state == "present" and op_check.rc != 0

# Uninstall tasks
- name: Uninstall 1Password CLI
  ansible.builtin.debug:
    msg: "To uninstall 1Password CLI on Darwin, please remove it from your Brewfile and run 'brew bundle cleanup --force'"
  when: op_state == "absent"
