---
- name: Check if op CLI is installed
  ansible.builtin.command: which op
  register: op_check
  changed_when: false
  failed_when: false
  when: op_state == "present"

- name: Download 1Password CLI package
  when: op_state == "present" and op_check.rc != 0
  ansible.builtin.get_url:
    url: "https://cache.agilebits.com/dist/1P/op2/pkg/{{ op_version }}/op_apple_universal_{{ op_version | replace('v', '') }}.pkg"
    dest: "/tmp/op_apple_universal_{{ op_version | replace('v', '') }}.pkg"
    mode: "0644"

- name: Install 1Password CLI package
  when: op_state == "present" and op_check.rc != 0
  ansible.builtin.command:
    cmd: "installer -pkg /tmp/op_apple_universal_{{ op_version | replace('v', '') }}.pkg -target /"
  become: true

- name: Verify 1Password CLI installation
  when: op_state == "present" and op_check.rc != 0
  ansible.builtin.command: which op
  register: op_verify
  changed_when: false
  failed_when: op_verify.rc != 0

# Uninstall tasks
- name: Check if op CLI exists
  ansible.builtin.stat:
    path: "/usr/local/bin/op"
  register: op_binary
  when: op_state == "absent"

- name: Remove 1Password CLI binary
  ansible.builtin.file:
    path: "/usr/local/bin/op"
    state: absent
  become: true
  when: op_state == "absent" and op_binary.stat.exists | default(false)

# Cleanup tasks
- name: Clean up temporary files
  ansible.builtin.file:
    path: "/tmp/op_apple_universal_{{ op_version | replace('v', '') }}.pkg"
    state: absent
