---
- name: Check if rustup is installed
  ansible.builtin.command: which rustup
  register: rustup_check
  failed_when: false
  changed_when: false

- name: Download rustup installer
  ansible.builtin.get_url:
    url: "https://static.rust-lang.org/rustup/dist/{{ ansible_architecture }}-unknown-linux-gnu/rustup-init"
    dest: /tmp/rustup-init
    mode: "0755"
  when: rustup_check.rc != 0
  register: download_rustup

- name: Install rustup
  ansible.builtin.shell: /tmp/rustup-init -y
  register: rustup_install
  when: rustup_check.rc != 0
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"

- name: Log rustup installation status
  ansible.builtin.debug:
    msg: "{{ 'rustup installed successfully' if rustup_install is changed else 'rustup is already installed' }}"

- name: Install Rust dependencies (Linux only)
  when: ansible_os_family == "Debian"
  become: true
  block:
    - name: Install build-essential
      apt:
        name: build-essential
        state: present
        update_cache: true
      register: rust_deps

    - name: Log Rust dependencies installation status
      debug:
        msg: "{{ 'Rust dependencies installed successfully' if rust_deps is changed else 'Rust dependencies were already installed' }}"

- name: Clean up rustup installer
  ansible.builtin.file:
    path: /tmp/rustup-init
    state: absent
  when: download_rustup is changed
