---
# Default state for fastfetch installation
fastfetch_state: present
fastfetch_version: "2.37.0"

# Architecture-specific settings
fastfetch_arch: "{{ 'aarch64' if ansible_architecture == 'arm64' or ansible_architecture == 'aarch64' else 'amd64' }}"
fastfetch_archive_url: "https://github.com/fastfetch-cli/fastfetch/releases/download/{{ fastfetch_version }}/fastfetch-linux-{{ fastfetch_arch }}.tar.gz"
fastfetch_bin_path: "/usr/local/bin/fastfetch"
