---
- name: Install helix-gpt
  block:
    - name: Clone helix-gpt repository
      ansible.builtin.git:
        repo: https://github.com/leona/helix-gpt.git
        dest: "{{ helix_source_dir }}-gpt"
        version: master
        force: true
      when: not helix_use_ghq
      ignore_errors: true

    - name: Clone helix-gpt using ghq
      ansible.builtin.shell: |-
        {% if ansible_os_family == 'Darwin' %}
        # Use Homebrew environment
        eval "$(/opt/homebrew/bin/brew shellenv)"
        {% endif %}
        # Attempt clone/update silently
        ghq get -u https://github.com/leona/helix-gpt.git >/dev/null 2>&1 || \
        ghq get https://github.com/leona/helix-gpt.git >/dev/null 2>&1 || \
        echo "Continuing without repository update"
      register: clone_result
      changed_when: false
      when: helix_use_ghq
      ignore_errors: true
      environment:
        PATH: "{{ '/opt/homebrew/bin:' + ansible_env.PATH if ansible_os_family == 'Darwin' else ansible_env.PATH }}"

    - name: Set helix-gpt directory path
      ansible.builtin.set_fact:
        helix_gpt_dir: "{{ ghq_root | default(helix_source_dir + '-gpt') }}/github.com/leona/helix-gpt"
      when: helix_use_ghq

    - name: Set helix-gpt directory path (non-ghq)
      ansible.builtin.set_fact:
        helix_gpt_dir: "{{ helix_source_dir }}-gpt"
      when: not helix_use_ghq

    - name: Build helix-gpt
      ansible.builtin.shell: |-
        {% if ansible_os_family == 'Darwin' %}
        # Use Homebrew environment
        eval "$(/opt/homebrew/bin/brew shellenv)"
        eval "$(/opt/homebrew/bin/fnm env --use-on-cd)"
        {% else %}
        # Use system paths
        export PATH="{{ ansible_env.HOME }}/.local/bin:$PATH"
        export PATH="{{ ansible_env.HOME }}/.cargo/bin:$PATH"
        eval "$(fnm env --use-on-cd)"
        {% endif %}
        # Install and build silently
        bun install >/dev/null 2>&1 || echo "Continuing without bun install"
        bun build:bin >/dev/null 2>&1 || echo "Continuing without build"
      args:
        chdir: "{{ helix_gpt_dir }}"
      register: build_result
      changed_when: false
      ignore_errors: true
      environment:
        PATH: "{{ '/opt/homebrew/bin:' + ansible_env.PATH if ansible_os_family == 'Darwin' else ansible_env.PATH }}"

    - name: Install helix-gpt binary
      ansible.builtin.copy:
        src: "{{ helix_gpt_dir }}/dist/helix-gpt"
        dest: "{{ helix_bin_dir }}/helix-gpt"
        mode: "0755"
        remote_src: true
      ignore_errors: true
