---
- name: Install packages with uv
  ansible.builtin.shell: |
    export PATH="{{ ansible_env.HOME }}/.local/bin:$PATH"
    uv tool install {{ item }}
  loop: "{{ helix_pip_packages }}"
  register: uv_install
  failed_when: false
  changed_when: uv_install.rc == 0
  when: helix_state == "present"
  ignore_errors: true
