---
- name: Node Exporter | Stop service
  ansible.builtin.service:
    name: node_exporter
    state: stopped
    enabled: false
  ignore_errors: true
  become: true

- name: Node Exporter | Remove systemd service file
  ansible.builtin.file:
    path: /etc/systemd/system/node_exporter.service
    state: absent
  become: true

- name: Node Exporter | Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Node Exporter | Remove binary
  ansible.builtin.file:
    path: "{{ node_exporter_install_dir }}/node_exporter"
    state: absent
  become: true

- name: Node Exporter | Remove user
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    state: absent
    remove: true
  become: true
