---
- name: Install docker and docker-compose
  hosts: all

  roles:
    # https://github.com/geerlingguy/ansible-role-docker
    - role: geerlingguy.docker
      vars:
        docker_users:
          - "{{ instance_owner }}"
        # docker_daemon_options:
        #   storage-driver: "devicemapper"
        #   log-opts:
        #     max-size: "100m"
