---
- name: Install pyenv
  hosts: all

  roles:
    # https://github.com/staticdev/ansible-role-pyenv
    - role: staticdev.pyenv
      vars:
        pyenv_version: "HEAD"
        pyenv_env: "user"
        pyenv_shellrc_file: "/home/{{ instance_owner }}/.bashrc"
        pyenv_path: "/home/{{ instance_owner }}/.pyenv"
        pyenvrc_path: "/home/{{ instance_owner }}"
        pyenv_owner: "{{ instance_owner }}"
        pyenv_global:
          - 3.11.2
        pyenv_enable_autocompletion: false
        pyenv_python_versions:
          - 3.11.2
        pyenv_virtualenvs:
          - venv_name: homelab
            py_version: 3.11.2
