---
- name: Update packages via apt or yum depending on distro
  hosts: all

  tasks:
    - name: Update apt packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      notify: Send notification to ntfy
      when: ansible_distribution in ["Debian", "Ubuntu"]
      tags: apt

    - name: Update yum packages
      become: true
      ansible.builtin.yum:
        update_cache: true
      notify: Send notification to ntfy
      when: ansible_distribution in ["Amazon", "CentOS", "OracleLinux"]
      tags: yum

  handlers:
    # - name: Send notification to Gotify
    #   ansible.builtin.uri:
    #     url: "https://gotify.timmybtech.com/message?token={{ gotify_token }}"
    #     method: POST
    #     body_format: form-urlencoded
    #     body:
    #       title: "Ansible Update"
    #       message: "{{ ansible_distribution }} packages have been updated on {{ ansible_hostname }}"
    #       priority: "5"

    - name: Send notification to ntfy
      ansible.builtin.uri:
        url: "https://ntfy.timmybtech.com/{{ ntfy_topic }}?auth={{ ntfy_token }}"
        method: POST
        headers:
          X-Title: "Ansible Update"
        body: "{{ ansible_distribution }} packages have been updated on {{ ansible_hostname }}"
