---
# Node.js setup configuration
node_setup_state: present # Can be 'present' or 'absent'
node_version: "20"

# npm packages configuration
npm_packages_state: latest # Can be 'present', 'latest', or 'absent'
gist_base_url: "https://gist.githubusercontent.com/timmyb824/807597f33b14eceeb26e4e6f81d45962/raw"
