---
- name: Alloy | Stop alloy service
  ansible.builtin.service:
    name: alloy
    state: stopped
    enabled: no
  ignore_errors: true
  become: true

- name: Alloy | Remove alloy package
  ansible.builtin.apt:
    name: alloy
    state: absent
    purge: true
  become: true

- name: Alloy | Remove /etc/alloy directory
  ansible.builtin.file:
    path: /etc/alloy
    state: absent
  become: true

- name: Alloy | Remove /etc/default/alloy
  ansible.builtin.file:
    path: /etc/default/alloy
    state: absent
  become: true

- name: Alloy | Autoremove unused packages
  ansible.builtin.apt:
    autoremove: true
  become: true

- name: Reload systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
