---
- name: Alloy | Update package cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Alloy | Upgrade alloy
  ansible.builtin.apt:
    name: alloy
    state: latest
  become: true
  notify: Restart alloy
