---
- name: Check if /usr/local/bin/curl exists
  ansible.builtin.stat:
    path: /usr/local/bin/curl
  register: local_curl
  when: inventory_hostname in groups['vagrant']

- name: Temporarily move /usr/local/bin/curl if it exists
  ansible.builtin.command: mv /usr/local/bin/curl /usr/local/bin/curl.bak
  become: true
  when:
    - inventory_hostname in groups['vagrant']
    - local_curl.stat.exists | default(false)
  register: curl_moved

- name: Get which curl is being used
  ansible.builtin.command: which curl
  register: curl_path
  changed_when: false
  when: inventory_hostname in groups['vagrant']

- name: Check for pipx installation
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/bin/pipx"
  register: pipx_check

- name: Uninstall all pipx packages if present
  ansible.builtin.shell: |
    export PATH="{{ ansible_env.HOME }}/.local/bin:$PATH"
    {{ ansible_env.HOME }}/.local/bin/pipx uninstall-all
  when:
    - pipx_check.stat.exists
    - uv_state == "present"
  register: pipx_uninstall
  changed_when: pipx_uninstall.rc == 0
  failed_when: false

- name: Check for pyenv installation
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"
  register: pyenv_check

- name: Remove pyenv if present
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.pyenv"
    state: absent
  when:
    - pyenv_check.stat.exists
    - uv_state == "present"
  register: pyenv_remove
  changed_when: pyenv_remove.changed

- name: Restore /usr/local/bin/curl if it was moved
  ansible.builtin.command: mv /usr/local/bin/curl.bak /usr/local/bin/curl
  become: true
  when:
    - inventory_hostname in groups['vagrant']
    - curl_moved is defined
    - curl_moved.changed
