---
dependencies:
  - role: homebrew
    when: ansible_os_family == "Darwin"

galaxy_info:
  role_name: go_packages
  description: Install Go and Go packages
  author: Timothy Bryant
  license: MIT
  min_ansible_version: "2.1"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: MacOS
      versions:
        - all
  galaxy_tags:
    - go
    - golang
    - development
