---
- name: Check system compatibility
  ansible.builtin.set_fact:
    logdy_supported: "{{ ansible_system == 'Linux' }}"

- name: Warn if system is not supported
  ansible.builtin.debug:
    msg: "Logdy installation is not supported on {{ ansible_system }}. Only Linux is supported."
  when: not logdy_supported

- name: Install logdy
  when:
    - logdy_state == 'present'
    - logdy_supported
  block:
    - name: Set binary name based on architecture
      ansible.builtin.set_fact:
        logdy_binary_name: "logdy_linux_{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

    - name: Download logdy binary
      ansible.builtin.get_url:
        url: "https://github.com/logdyhq/logdy-core/releases/download/v{{ logdy_version }}/{{ logdy_binary_name }}"
        dest: "{{ logdy_install_dir }}/logdy"
        mode: "0755"
        force: true
      become: true

- name: Uninstall logdy
  when: logdy_state == 'absent'
  become: true
  ansible.builtin.file:
    path: "{{ logdy_install_dir }}/logdy"
    state: absent
