---
- name: Skip logdy installation on Darwin
  ansible.builtin.debug:
    msg: "Skipping logdy installation on Darwin - managed through Homebrew"
  when: ansible_os_family == "Darwin"

- name: Install logdy on Linux
  when:
    - ansible_os_family != "Darwin"
    - logdy_state == 'present'
  block:
    - name: Set binary name based on architecture
      ansible.builtin.set_fact:
        logdy_binary_name: "logdy_linux_{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

    - name: Download logdy binary
      ansible.builtin.get_url:
        url: "https://github.com/logdyhq/logdy-core/releases/download/v{{ logdy_version }}/{{ logdy_binary_name }}"
        dest: "{{ logdy_install_dir }}/logdy"
        mode: "0755"
        force: true
      become: true

- name: Uninstall logdy on Linux
  when:
    - ansible_os_family != "Darwin"
    - logdy_state == 'absent'
  become: true
  ansible.builtin.file:
    path: "{{ logdy_install_dir }}/logdy"
    state: absent
