---
k3s_version: v1.26.1+k3s1
ansible_user: "{{ lookup('env','USER') }}"
systemd_dir: /etc/systemd/system
system_timezone: "America/New_York"

flannel_iface: "eth0"

apiserver_endpoint: "192.168.86.219"

# K3S_TOKEN is required  masters can talk together securely
# this token should be alpha numeric only
# K3S_TOKEN: "some-password-here-here-here"
K3S_TOKEN: "{{ lookup('env','K3S_TOKEN') }}"

# change these to your liking, the only required one is--disable servicelb
# with additional extra_server_args: "--disable servicelb --disable traefik --write-kubeconfig-mode 644 --kube-apiserver-arg default-not-ready-toleration-seconds=30 --kube-apiserver-arg default-unreachable-toleration-seconds=30 --kube-controller-arg node-monitor-period=20s --kube-controller-arg node-monitor-grace-period=20s --kubelet-arg node-status-update-frequency=5s"
# added these extra_server_args: for prometheus stack monitoring:  --kube-controller-manager-arg bind-address=0.0.0.0 --kube-proxy-arg metrics-bind-address=0.0.0.0 --kube-scheduler-arg bind-address=0.0.0.0 --etcd-expose-metrics true --kubelet-arg containerd=/run/k3s/containerd/containerd.sock
## If you want to add arguments after running the playbook then you may find it easier to add them via systemd at /etc/systemd/system/k3s.service (don't forget to reload and restart)
extra_server_args: "--disable servicelb --disable traefik --write-kubeconfig-mode 644 --kube-controller-manager-arg bind-address=0.0.0.0 --kube-proxy-arg metrics-bind-address=0.0.0.0 --kube-scheduler-arg bind-address=0.0.0.0 --etcd-expose-metrics true --kubelet-arg containerd=/run/k3s/containerd/containerd.sock"
# possible extra_agent_args: "--kubelet-arg node-status-update-frequency=5s"
extra_agent_args: ""

kube_vip_tag_version: "v0.5.0"

## METAL LB DEPLOYED ON ITS OWN
## IF RE-USING THESE PLAYBOOKS MUST ENSURE METALLB IS NOT DEPLOYED AS PART OF K3S
# # image tag for metal lb
# metal_lb_speaker_tag_version: "v0.13.4"
# metal_lb_controller_tag_version: "v0.13.4"

# # metallb ip range for load balancer
# metal_lb_ip_range: "192.168.86.220-192.168.86.224"
