---
- name: Add Tailscale repository signing key
  ansible.builtin.get_url:
    url: "{{ tailscale_repo_url }}/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.noarmor.gpg"
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: "0644"
  become: true
  when: tailscale_state == "present"

- name: Add Tailscale repository
  ansible.builtin.get_url:
    url: "{{ tailscale_repo_url }}/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.tailscale-keyring.list"
    dest: /etc/apt/sources.list.d/tailscale.list
    mode: "0644"
  become: true
  when: tailscale_state == "present"

- name: Install Tailscale package
  ansible.builtin.apt:
    name: tailscale
    state: "{{ tailscale_state }}"
    update_cache: yes
  become: true

- name: Remove Tailscale repository and key
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apt/sources.list.d/tailscale.list
    - /usr/share/keyrings/tailscale-archive-keyring.gpg
  become: true
  when: tailscale_state == "absent"
