---
- name: Skip rbenv installation on Darwin
  ansible.builtin.debug:
    msg: "Skipping rbenv installation on Darwin - managed through Homebrew"
  when: rbenv_state == "present"

- name: Initialize Homebrew environment
  ansible.builtin.shell: eval "$(/opt/homebrew/bin/brew shellenv)" && echo $PATH
  register: brew_env
  changed_when: false
  when: rbenv_state == "present"

- name: Check if rbenv is available
  ansible.builtin.shell: |
    eval "$(/opt/homebrew/bin/brew shellenv)"
    which rbenv
  register: rbenv_check
  changed_when: false
  failed_when: false

- name: Fail if rbenv is not installed
  ansible.builtin.fail:
    msg: "rbenv could not be found. Please ensure it's installed via Homebrew."
  when: rbenv_check.rc != 0 and rbenv_state == "present"

- name: Uninstall rbenv on MacOS
  when: rbenv_state == "absent"
  block:
    - name: Remove rbenv directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.rbenv"
        state: absent
