---
- name: Update Homebrew and Upgrade Packages
  hosts: all
  gather_facts: false

  tasks:
    - name: Update Homebrew and Upgrade Packages
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
        path: "/usr/local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin"
