---
galaxy_info:
  role_name: homebrew
  author: Timothy Bryant
  description: Installs and configures Homebrew and manages packages
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Darwin
      versions:
        - all

dependencies: []
